FROM rust

WORKDIR /server

# install dependencies seperately for caching
# COPY "Cargo.toml" .
# RUN echo "fn main() {}" > dummy.rs
# RUN sed -i 's#src/main.rs#dummy.rs#' Cargo.toml
# RUN cargo build
# RUN sed -i 's#dummy.rs#src/main.rs#' Cargo.toml

# copy files
COPY . .

CMD "cargo" "run"